### PR TITLE
Fix circular dependency warning

### PR DESCRIPTION
**Pull request by steigr**
lib/consul/client.rb:34: warning: circular argument reference - http

Signed-off-by: steigr me@stei.gr

### CODE REVIEW

**Comment by xaviershay** [comment]
weird.

fwiw I think there is a better client out there that you probably want to use for reals.

**Comment by grosser** [comment]
@xaviershay can you release this please ? latest version on rubygems still has it :(

**Comment by xaviershay** [comment]
Done, 0.1.2.

**Comment by grosser** [comment]
❤️

**Pull request merged**
